Nike/Models/KhachHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nike.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.Order = new HashSet<Order>();
        }

        public string oldPassword { get; set; }

        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int idUser { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Tên")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Vui lòng nhập tên thật")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Họ")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Vui lòng nhập họ thật")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Email")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Mật khẩu")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$", ErrorMessage = "Mật khẩu tối thiểu 8 kí tự, bao gồm 1 in hoa, 1 số và 1 ký tự đặc biệt")]
        public string Password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Vui lòng nhập Nhập lại mật khẩu")]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "Mật khẩu không trùng khớp")]
        public string ConfirmPassword { get; set; }
        public string FullName()
        {
            return this.LastName + " " + this.FirstName;
        }

        public string Picture { get; set; }

        public string Address { get; set; }
        //[Required(ErrorMessage = "Vui lòng nhập ngày sinh")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{mm/dd/yyyy}")]
        public Nullable<System.DateTime> NgaySinh { get; set; }

        public string CMT { get; set; }

        public string Sdt { get; set; }
        public int TichLuy { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
    public partial class EditProFile
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int idUser { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Tên")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Vui lòng nhập tên thật")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Họ")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Vui lòng nhập họ thật")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Email")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string Email { get; set; }
        public string FullName()
        {
            return this.LastName + " " + this.FirstName;
        }

        public string Picture { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        public string Address { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số chứng minh thư")]
        public string CMT { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        public string Sdt { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }

    public partial class ChangePassword
    {
        public int idUser { get; set; }

        public string oldPassword { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Mật khẩu")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$", ErrorMessage = "Mật khẩu tối thiêu 8 kí tự, bao gồm 1 in hoa, 1 số và 1 ký tự đặc biệt")]
        public string Password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Vui lòng nhập nhập lại mật khẩu")]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "Mật khẩu không trùng khớp")]
        public string ConfirmPassword { get; set; }
    }
}

Nike/Areas/Admin/Controllers/KhachHangController.cs
using Nike.DesignPattern;
using Nike.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Nike.Areas.Admin.Controllers
{
    public class KhachHangController : Controller
    {
		// GET: Admin/KhachHang
		private readonly QuanLySanPhamEntities _db = DbContextSingleton.GetInstance();
		public ActionResult Index(string searchStr)
        {
            NhanVien nv = (NhanVien)Session["NV"];
            if (nv.MaChucVu == 1)
            {
                return RedirectToAction("Index", "Order");
            }
            var dsKhachHang = _db.KhachHang.ToList();

            // Tìm kiếm khách hàng trong quản lí khách hàng bằng email 
            if (!String.IsNullOrEmpty(searchStr))
            {
                searchStr = searchStr.ToLower();
                dsKhachHang = dsKhachHang.Where(s => s.Email.ToLower().Contains(searchStr)).ToList();
                ViewBag.dsKh = dsKhachHang;
            }
            else
            {
                ViewBag.dsKH = dsKhachHang;
            }

            return View();
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachhang = _db.KhachHang.Find(id);
            if (khachhang == null)
            {
                return HttpNotFound();
            }
            return View(khachhang);
        }
    }
}

Nike/Areas/Admin/Views/KhachHang/Detail.cshtml
@model Nike.Models.KhachHang
@{

    ViewBag.Title = "Thông tin cá nhân khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_layoutadmin.cshtml";
}

<div class="app-title">
    <ul class="app-breadcrumb breadcrumb side">
        <li class="breadcrumb-item active"><a href="#"><b>Khách hàng: #@Model.idUser</b></a></li>
    </ul>
    <div id="clock"></div>
</div>

<div class="row detail">
        <div class="col-md-4 detail__avatar">
            <img src="~/Hinh/KhachHang/@Model.Picture" alt="Ảnh đại diện" />
        </div>
        <div class="col-md-8">
            <div class="detail__item">
                <label class="control-label">Họ và tên: </label>
                @Model.FullName()
            </div>
            <div class="detail__item">
                <label class="control-label">Email: </label>
                @Model.Email
            </div> <div class="detail__item">
                <label class="control-label">Địa chỉ thường trú: </label>
                @Model.Address
            </div> <div class="detail__item">
                <label class="control-label">Ngày sinh: </label>
                @(Model.NgaySinh?.ToString("dd/MM/yyyy"))
            </div> <div class="detail__item">
                <label class="control-label">Số điện thoại: </label>
                @Model.Sdt
            </div>
            <div class="detail__item">
                <label class="control-label">Số chứng minh thư: </label>
                @Model.CMT
            </div>
            <div class="row btn">
                <button class="btn btn-save btn-sm edit" type="button" title="Sửa"
                        onclick="location.href='@Url.Action("Edit", "KhachHang",new { id = Model.idUser })'">
                    Chỉnh sửa thông tin
                </button>
                <a class="btn btn-cancel" href="@Url.Action("Index","KhachHang")">Hủy bỏ</a>
            </div>
        </div> 

     
    </div>

    <style>
        .detail {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        detail__avatar {
        }

        .detail__avatar img {
            height: 80%;
            width: 80%;
            object-fit: cover;
        }

        .detail__item {
            margin: 20px 0;
            display: block;
            width: 100%;
            padding: 0.375rem 0.75rem;
            font-size: 15px;
            line-height: 1.5;
            color: black;
            background-color: #f1f1f1;
            background-clip: padding-box;
            height: 45px;
            border: 1px solid #dadada;
            border-radius: .357rem;
        }
    </style>

Nike/Areas/Admin/Views/KhachHang/Index.cshtml
@model IEnumerable<Nike.Models.KhachHang>

@{
    ViewBag.Title = "Quản lí khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_layoutadmin.cshtml";
}

<div class="app-title">
    <ul class="app-breadcrumb breadcrumb side">
        <li class="breadcrumb-item active"><a href="#"><b>Danh sách khách hàng</b></a></li>
    </ul>
    <div id="clock"></div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">

                <div class="row">
                    <div class="col-sm-12 col-md-6">

                    </div>
                    <div class="col-sm-12 col-md-6">
                        @using (Html.BeginForm("Index", "KhachHang", FormMethod.Get, new { @class = "dataTables_filter d-flex justify-content-end" }))
                        {
                            <label>
                                Tìm kiếm:

                                @Html.TextBox("searchStr", null, new { @class = "form-control form-control-sm", @placeholder = "Email khách hàng" })

                            </label>
                        }
                    </div>
                </div>
                <dov class="row">
                    <table class="table table-hover table-bordered js-copytextarea" cellpadding="0" cellspacing="0" border="0"
                           id="sampleTable">
                        <thead>
                            <tr>

                                <th>
                                    Họ Tên
                                </th>

                                <th>
                                    Email
                                </th>
                                <th>
                                    Ảnh đại diện
                                </th>
                                <th>
                                    Địa chỉ
                                </th>
                                <th>
                                    Loại khách hàng
                                </th>
                                <th>
                                    Số điện thoại
                                </th>
                                <th>
                                    Chức năng
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.dsKH)
                            {
                                <tr>
                                    <td>
                                        @item.FullName()
                                    </td>
                                    <td>
                                        @if (@item.Email == null)
                                        {
                                            <p>Không có email</p>
                                        }
                                        else
                                        {
                                            @item.Email
                                        }
                                    </td>
                                    <td>
                                        @if ((item.Picture) != null)
                                        {
                                            <img src="~/Hinh/KhachHang/@Url.Content(@item.Picture)" width="100" height="100" />
                                        }
                                        else
                                        {
                                            <img src="~/Hinh/NhanVien/default.png" width="100" height="100" />

                                        }
                                    </td>
                                    <td>
                                        @item.Address
                                    </td>
                                    <td>
                                        @if (item.TichLuy < 50)
                                        {
                                            <p>Khách hàng vãng lai</p>
                                        }
                                        else if (item.TichLuy < 100)
                                        {
                                            <p>Khách hàng bạc</p>
                                        }
                                        else if (item.TichLuy < 150)
                                        {
                                            <p>Khách hàng vàng  </p>
                                        }
                                        else
                                        {
                                            <p>Khách hàng kim cương</p>
                                        }

                                    </td>
                                    <td>
                                        @item.Sdt
                                    </td>
                                    <td class="table-td-center">
                                        <button class="btn btn-primary btn-sm user-btn" type="button" title="Xem thông tin"
                                                    onclick="location.href='@Url.Action("Detail", "KhachHang",new { Id = item.idUser })'">
                                            <i class="fas fa-user"></i>
                                        </button>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </dov>

            </div>
        </div>
    </div>
</div>