Nike/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CatalogId { get; set; }
        public string Picture { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public Nullable<double> PriceOld { get; set; }
        public string ProductSale { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ProductSold { get; set; }
        public Nullable<System.DateTime> NgayNhapHang { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
    }
}

Nike/Areas/Admin/Controllers/CatalogController.cs
using Nike.DesignPattern;
using Nike.DesignPattern.ProductModel;
using Nike.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Nike.Areas.Admin.Controllers
{
    //Proxy
   
    public class CatalogController : Controller
    { // GET: Catalog
        private readonly QuanLySanPhamEntities _db = DbContextSingleton.GetInstance();
		public ActionResult Index()
        {
            NhanVien nv = (NhanVien)Session["NV"];
            if (nv.MaChucVu == 1)
            {
                return RedirectToAction("Index", "Home");
            }
            var catalog = (from s 
                           in _db.Catalog 
                           select s).ToList();
            ViewBag.catalogs = catalog;
            return View();

        }
      
        [HttpPost]
        public ActionResult Create(Catalog model)
        {
            var catalogs = (from s in _db.Catalog select s).ToList();
            model.ID = catalogs.Last().ID + 1;
            // lưu dữ liệu vào db
            if (string.IsNullOrEmpty(model.CatalogCode) && string.IsNullOrEmpty(model.CatalogName) == true)
            {
                ModelState.AddModelError("", "Mã danh mục không được để trống");
                return View(model);
            }
            _db.Catalog.Add(model);
            _db.SaveChanges();

            if (model.ID > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Không lưu vào được database");
                return View(model);
            }
        }
        public ActionResult Edit(int ID)
        {
            if (ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Catalog catalog = _db.Catalog.Find(ID);
            if (catalog == null)
            {
                return HttpNotFound();
            }
            return View(catalog);
        }
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost([Bind(Include = "ID,CatalogCode,CatalogName")] Catalog catalogs)
        {
            Catalog catalog = _db.Catalog.Find(catalogs.ID);
            if (ModelState.IsValid)
            {
                catalog.ID = catalogs.ID;
                catalog.CatalogCode = catalogs.CatalogCode;
                catalog.CatalogName = catalogs.CatalogName;
                _db.Entry(catalog).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(catalog);
        }
        public ActionResult Delete(int ID)
        {

            if (ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Catalog catalog = _db.Catalog.Find(ID);
            if (catalog == null)
            {
                return HttpNotFound();
            }
            return View(catalog);
        }
        // POST: KhachHang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int ID)
        {
            Catalog catalog = _db.Catalog.Find(ID);
            _db.Catalog.Remove(catalog);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Nike/Areas/Admin/Controllers/ProductController.cs
using Nike.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.IO;
using System.Net;
using System.Data.Entity;
using Nike.DesignPattern;
using Nike.DesignPattern.ProductModel;
using System.Threading.Tasks;

namespace Nike.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        // GET: Admin/Product
        private readonly QuanLySanPhamEntities _db = DbContextSingleton.GetInstance();
        // GET: Product


        public ActionResult Index(string sort, int? page, string searchString)
        {
            const int pageSize = 10;
            int pageNumber = page ?? 1;

            var products = _db.Product.ToList();

            // tìm kiếm sản phẩm 
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                ViewBag.searchStr = searchString;
                products = products.Where(p => p.ProductName.ToLower().Contains(searchString) ||
                                                p.Catalog.CatalogName.ToLower().Contains(searchString))
                                                .ToList();
            }
            // sắp xếp sản phẩm
            else
            {
                ViewBag.Sort = sort;
                switch (sort)
                {
                    case "pre-sold":
                        products = products.Where(p => p.SoLuong < 50 && p.SoLuong > 0).ToList();
                        break;
                    case "sold":
                        products = products.Where(p => p.SoLuong == 0).ToList();
                        break;
                    case "now":
                        products = products.OrderByDescending(p => p.NgayNhapHang).ToList();
                        break;
                    default:
                        products = products.ToList();
                        break;
                }
            }


            ViewBag.totalPage = Math.Ceiling((double)products.Count() / pageSize);
            ViewBag.products = products.ToPagedList(pageNumber, pageSize);

            return View(ViewBag.products);
        }

        //Proxy
        public interface IProductProxy
        {
            int AddProduct(Product model);
        }
        public class ProductRepositoryProxy : IProductProxy
        {
            private readonly QuanLySanPhamEntities _db = DbContextSingleton.GetInstance();
            public int AddProduct(Product model)
            {
                if (model.PriceOld < 0 || model.SoLuong > 100)
                {
                    return -1;
                }
                var productId = _db.Product.Add(model);
                return productId.Id;
            }
        }
        //--------------------------------------------------------------------------------\\

        // Tạo sản phẩm mới 
        public ActionResult Create()
        {
            ViewBag.CatalogId = new SelectList(_db.Catalog, "ID", "CatalogName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file, [Bind(Include = "CatalogId,ProductName,ProductCode,UnitPrice,SoLuong,ProductSold,ProductSale,PriceOld")] Product model)
        {

            if (ModelState.IsValid)
            {
                String anh = "/Hinh/Product/hinhphone.jpg";
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    String path = System.IO.Path.Combine(
                                           Server.MapPath("~/Hinh"), pic);
                    file.SaveAs(path);
                    anh = pic;
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }

                //Proxy 
                ProductRepositoryProxy productRepositoryProxy = new ProductRepositoryProxy();
                productRepositoryProxy.AddProduct(model);
                model.NgayNhapHang = DateTime.Now;
                model.Picture = anh;
                Random prCode = new Random();
                model.ProductCode = String.Concat("PR", prCode.Next(5000, 7000).ToString());
                model.ProductSold = 0;
                model.UnitPrice = model.ProductSale != null
                    ? (model.UnitPrice = model.PriceOld - (model.PriceOld * int.Parse(model.ProductSale)) / 100)
                    : model.UnitPrice = model.PriceOld;
                _db.Product.Add(model);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CatalogId = new SelectList(_db.Catalog, "ID", "CatalogName", model.CatalogId);
            return View(model);
        }
        //---------------------------------------------------------------------//

        ///Mẫu Builder
        public class ProductBuilder
        {
            private Product _product;

            public ProductBuilder()
            {
                _product = new Product();
            }

            public ProductBuilder SetCatalogId(int? catalogId)
            {
                _product.CatalogId = catalogId;
                return this;
            }

            public ProductBuilder SetProductName(string productName)
            {
                _product.ProductName = productName;
                return this;
            }

            // Thêm các phương thức khác cho các thuộc tính khác

            public Product Build()
            {
                return _product;
            }
        }
        // Chức năng sửa thông tin sản phẩm 
        public ActionResult Edit(int Id)
        {


            if (Id.ToString() == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = _db.Product.Find(Id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CatalogId = new SelectList(_db.Catalog, "ID", "CatalogName", product.CatalogId);
            return View(product);
        }

        //Mẫu Builder
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CatalogId,Picture,ProductName,ProductCode,PriceOld,UnitPrice,ProductSold,ProductSale,SoLuong")] Product product, HttpPostedFileBase file)
        {
            Product pr = _db.Product.Find(product.Id);
            if (ModelState.IsValid)
            {
                String anh = pr.Picture;
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    String path = System.IO.Path.Combine(
                                           Server.MapPath("~/Hinh"), pic);
                    file.SaveAs(path);
                    anh = pic;
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }

                  pr = new ProductBuilder()
                    .SetCatalogId(product.CatalogId)
                    .SetProductName(product.ProductName)
                    .Build();

                pr.Picture = anh;
                pr.CatalogId = product.CatalogId;
                pr.ProductName = product.ProductName;
                pr.PriceOld = product.PriceOld;
                pr.UnitPrice = (pr.ProductSale != null) ? (pr.UnitPrice = (pr.PriceOld - (pr.PriceOld * int.Parse(pr.ProductSale)) / 100)) : (pr.UnitPrice = pr.PriceOld);
                pr.ProductCode = product.ProductCode;
                pr.ProductSold = product.ProductSold;
                pr.ProductSale = product.ProductSale;
                pr.SoLuong = 500 - pr.ProductSold;
                pr.NgayNhapHang = DateTime.Now;

                _db.Entry(pr).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CatalogId = new SelectList(_db.Catalog, "ID", "CatalogName", pr.CatalogId);
            return View(product);
        }

        //Design Pattern Command
        public interface ICommand
        {
            void Execute();
        }

        public class DeleteProductCommand : ICommand
        {
            private readonly QuanLySanPhamEntities _db;
            private readonly int _productId;

            public DeleteProductCommand(int productId)
            {
                _db = DbContextSingleton.GetInstance();
                _productId = productId;
            }

            public void Execute()
            {
                Product product = _db.Product.Find(_productId);
                if (product != null)
                {
                    _db.Product.Remove(product);
                    _db.SaveChanges();
                }
            }
        }
    }
}
        // Hàm xóa sản phẩm 
//        public ActionResult Delete(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            Product product = _db.Products.Find(id);
//            if (product == null)
//            {
//                return HttpNotFound();
//            }
//            return View(product);
//        }

//        [HttpPost, ActionName("Delete")]
//        [ValidateAntiForgeryToken]
//        public ActionResult DeleteConfirmed(int Id)
//        {
//            try
//            {
//                Product product = _db.Products.Find(Id);
//                _db.Products.Remove(product);
//                _db.SaveChanges();
//            }
//            catch
//            {

Nike/Areas/Admin/Views/Product/Create.cshtml
@model Nike.Models.Product

@{
    ViewBag.Title = "Thêm sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_layoutadmin.cshtml";
}

@using (Html.BeginForm("Create", "Product", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-md-12">
                <div class="tile">
                    <h3 class="tile-title">Tạo mới sản phẩm</h3>
                    <div class="tile-body">
                     
                        <div class="row">

                            <div class="form-group col-md-4">
                                <label class="control-label">Tên sản phẩm </label>
                                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group  col-md-4">
                                <label class="control-label">Số lượng</label>
                                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-md-4">
                                <label for="exampleSelect1" class="control-label">Danh mục</label>
                                @Html.DropDownList("CatalogId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.CatalogId, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-md-4 ">
                                <label for="exampleSelect1" class="control-label">Giảm giá (%)</label>
                                @Html.EditorFor(model => model.ProductSale, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ProductSale, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group col-md-4">
                                <label class="control-label">Giá vốn</label>
                                @Html.EditorFor(model => model.PriceOld, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PriceOld, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-md-4">
                                <label class="control-label">Ảnh sản phẩm</label>
                                <div id="myfileupload">
                                    <input type="file" name="file" id="file" style="width: 100%;" />
                                    @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
                                </div>
                                <div id="thumbbox">
                                    <img height="450" width="400" alt="Thumb image" id="thumbimage"
                                         style="display: none" />
                                    <a class="removeimg" href="javascript:"></a>
                                </div>
                                <div id="boxchoice">
                                    <a href="javascript:" class="Choicefile">
                                        <i class="fas fa-cloud-upload-alt"></i>
                                        Chọn ảnh
                                    </a>
                                    <p style="clear:both"></p>
                                </div>
                            </div>
                        </div>

                    </div>
                    <input type="submit" value="Tạo sản phẩm" class="btn btn-save" />
                    <a class="btn btn-cancel" href="@Url.Action("Index","Product")">Hủy bỏ</a>
                </div>
            </div>
        </div>
    </div>

}

Nike/Areas/Admin/Views/Product/Delete.cshtml
@model Nike.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_layoutadmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

        <dt>
            Tên sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            Mã Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductCode)
        </dd>


        <dt>
            Đã bán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductSold)
        </dd>

        <dt>
            Danh mục
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Catalog.CatalogName)
        </dd>

        <dt>
            Xuất xứ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Catalog.ProductOrigin)
        </dd>

        <dt>
            Giảm giá
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductSale)
        </dd>

        <dt>
            Giá vốn
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceOld)
        </dd>

        <dt>
            Giá bán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Nike/Areas/Admin/Views/Product/Index.cshtml
@using Nike.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<Nike.Models.Product>

@{
    ViewBag.Title = "Danh sách sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_layoutadmin.cshtml";
    var currentSearch = ViewBag.searchStr;
    var currentSort = ViewBag.Sort;
    var totalPage = ViewBag.totalPage;
    var dsProduct = ViewBag.products;
}



<div class="app-title">
    <ul class="app-breadcrumb breadcrumb side">
        <li class="breadcrumb-item active"><a href="#"><b>Danh sách sản phẩm</b></a></li>
    </ul>
    <div id="clock"></div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="row element-button">
                    <div class="col-sm-2">
                        <a class="btn btn-add btn-sm" href="@Url.Action("Index","Catalog")">
                            <i class="fas fa-folder-plus"></i> Danh sách danh mục
                        </a>
                    </div>
                    <div class="col-sm-2">
                        <a class="btn btn-delete print-file btn-sm" href="@Url.Action("Create","Product")">
                            <i class="fas fa-plus"></i>
                            Tạo mới sản phẩm
                        </a>
                    </div>
                    <div class="col-sm-2">
                        <a class="btn btn-warning btn-sm" href="@Url.Action("Index","Product", new {@sort = "pre-sold" })">
                            Sắp hết hàng
                        </a>
                    </div>
                    <div class="col-sm-2">
                        <a class="btn btn-danger btn-sm" href="@Url.Action("Index","Product", new {@sort = "sold" })">
                            Hết hàng
                        </a>
                    </div>
                    <div class="col-sm-2">
                        <a class="btn btn-light btn-sm" href="@Url.Action("Index","Product", new {@sort = "now" })">
                            Cập nhật lần cuối
                        </a>
                    </div>
                    <div class="col-sm-2">
                        <a class="btn btn-success btn-sm" href="@Url.Action("Index","Product")">
                            Mặc định
                        </a>
                    </div>
                </div>

                <div class="row" style="align-items:center">
                    <div class="col-sm-12 col-md-6">
                        <span>Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @totalPage</span>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        @* Tìm kiếm sản phẩm trong admin  *@
                        @using (Html.BeginForm("Index", "Product", FormMethod.Get, new { @class = "dataTables_filter d-flex justify-content-end" }))
                        {
                            <label>
                                Tìm kiếm:

                                @Html.TextBox("searchString", null, new { @class = "form-control form-control-sm", @placeholder = "Nhập tên hoặc nhãn hiệu" })

                            </label>
                        }
                    </div>
                </div>
                <table class="table table-hover table-bordered" id="sampleTable">
                    <thead>
                        <tr>

                            <th>Mã sản phẩm</th>
                            <th>Tên sản phẩm</th>
                            <th>Ảnh</th>
                            <th>Số lượng</th>
                            <th>Tình trạng</th>
                            <th>Giá tiền</th>
                            <th>Nhãn hiệu</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.products)
                        {
                            <tr>

                                <td>@item.ProductCode</td>
                                <td>@item.ProductName</td>
                                <td>
                                    @if (item.Picture == null)
                                    {
                                        <img src="~/Hinh/Product/hinhphone.jpg" alt="Image" width="100" height="100" />
                                    }
                                    else
                                    {
                                        <img src="~/Hinh/Product/@Url.Content(@item.Picture)" alt="Image" width="100" height="100" />
                                    }
                                </td>

                                <td>
                                    @if (@item.SoLuong >= 0)
                                    {
                                        @item.SoLuong
                                    }
                                    else
                                    { <p>0</p>}
                                </td>
                                <td>
                                    @{ if (item.SoLuong > 0 && item.SoLuong > 50)
                                        {
                                        <span class="badge bg-success">Còn hàng</span> }
                                        else if (item.SoLuong > 0 && item.SoLuong < 50)
                                        {
                                        <span class="badge badge-warning">Sắp hết hàng</span> }
                                        else 
                                        {
                                        <span class="badge bg-danger">Hết hàng</span>
                                        }
                                      }
                                </td>
                                <td>@string.Format("{0:#,0}", item.UnitPrice) đ</td>
                                <td>@item.Catalog.CatalogName</td>
                                <td>
                                    <button class="btn btn-primary btn-sm trash" type="button" title="Xóa"
                                            onclick="location.href='@Url.Action("Delete", "Product",new { id = item.Id })'">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                    <button class="btn btn-primary btn-sm edit" type="button" title="Sửa"
                                            onclick="location.href='@Url.Action("Edit", "Product",new { id = item.Id })'">
                                        <i class="fas fa-edit"></i>
                                    </button>

                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
                @* Tạo liên kết các trang *@
                @if (totalPage > 1)
                {
                    <div class="MenuTrang pagination">
                        @Html.PagedListPager(Model, page => Url.Action("Index", new {searchString = currentSearch , page = page }),
                          new PagedListRenderOptions()
                          {
                              LiElementClasses = new[] { "paginate_button page-item page-link" },
                              UlElementClasses = new[] { "pagination" }
                          })
                    </div>
                }


            </div>
        </div>
    </div>
</div>