Nike/Models/NhanVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Password { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Sdt { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}

Nike/Areas/Admin/Controllers/NhanVienController.cs
using Nike.DesignPattern;
using Nike.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Nike.Areas.Admin.Controllers
{
    public class NhanVienController : Controller
    {
		// GET: Admin/NhanVien
		private readonly QuanLySanPhamEntities _db = DbContextSingleton.GetInstance();
		// GET: Admin/NhanVien

		// Hiển thị giao diện Admin 
		public ActionResult Index(string searchString)
        {
            NhanVien nv = (NhanVien)Session["NV"];
            if (nv.MaChucVu == 1)
            {
                return RedirectToAction("Index", "Home");
            }
            var dsNhanVien = (from s in _db.NhanVien select s).ToList();
            // Tìm kiếm nhân viên trong quản lí nhân viên
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                ViewBag.NhanVien = dsNhanVien.Where(s => s.FullName.ToLower().Contains(searchString)).ToList();
            }
            else
            {
                ViewBag.NhanVien = dsNhanVien;
            }
            return View();
        }
        // Thêm nhân viên mới 
        public ActionResult Create()
        {
            ViewBag.MaChucVu = new SelectList(_db.ChucVu, "MaChucVu", "ChucVu1");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file, [Bind(Include = "FullName,Email,Address,NgaySinh,Password,MaChucVu,Sex,Sdt")] NhanVien nhanvien)
        {

            if (ModelState.IsValid)
            {
                String anh = "user.jpg";
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    String path = System.IO.Path.Combine(Server.MapPath("~/Hinh/NhanVien"), pic);
                    file.SaveAs(path);
                    anh = pic;
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }
                nhanvien.Picture = anh;
                _db.NhanVien.Add(nhanvien); // thêm đối tượng Link
                _db.SaveChanges(); // lưu lại
                return RedirectToAction("Index"); // quay trở về trang Index để xem kết quả thay đổi
            }
            ViewBag.MaChucVu = new SelectList(_db.ChucVu, "MaChucVu", "ChucVu1", nhanvien.MaChucVu);
            return View(nhanvien); // nếu không thể tạo mới thì trả về View như cũ
        }

        // Sửa thông tin nhân viên
        public ActionResult Edit(int id)
        {
            if (id.ToString() == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanvien = _db.NhanVien.Find(id);
            if (nhanvien == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaChucVu = new SelectList(_db.ChucVu, "MaChucVu", "ChucVu1", nhanvien.MaChucVu);
            return View(nhanvien);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FullName,Email,Address,NgaySinh,Password,MaChucVu,Picture,Sex,Sdt")] NhanVien nv, HttpPostedFileBase file)
        {

            NhanVien nhanvien = _db.NhanVien.Find(nv.Id);
            ViewBag.MaChucVu = new SelectList(_db.ChucVu, "MaChucVu", "ChucVu1", nhanvien.MaChucVu);
            if (ModelState.IsValid)
            {
                String anh = nhanvien.Picture;
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    String path = System.IO.Path.Combine(
                                           Server.MapPath("~/Hinh/NhanVien"), pic);
                    file.SaveAs(path);
                    anh = pic;
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }
                nhanvien.Picture = anh;
                nhanvien.FullName = nv.FullName;
                nhanvien.Email = nv.Email;
                nhanvien.Address = nv.Address;
                if (nv.NgaySinh != null)
                {
                    nhanvien.NgaySinh = nv.NgaySinh;
                }
                else
                {
                    nhanvien.NgaySinh = nhanvien.NgaySinh;
                }

                nhanvien.Password = nv.Password;
                nhanvien.MaChucVu = nv.MaChucVu;
                nhanvien.Sex = nv.Sex;
                nhanvien.Sdt = nv.Sdt;
                _db.Entry(nhanvien).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nv);

        }
        //Xóa nhân viên 
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanvien = _db.NhanVien.Find(id);
            if (nhanvien == null)
            {
                return HttpNotFound();
            }
            return View(nhanvien);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int Id)
        {
                NhanVien nhanvien = _db.NhanVien.Find(Id);
                _db.NhanVien.Remove(nhanvien);
                _db.SaveChanges();
                return RedirectToAction("Index");
        }


        // Xem chi tiết Nhân viên
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanvien = _db.NhanVien.Find(id);
            if (nhanvien == null)
            {
                return HttpNotFound();
            }
            return View(nhanvien);
        }
    }
}

Nike/Areas/Admin/Views/NhanVien/Create.cshtml
@model Nike.Models.NhanVien

@{
    ViewBag.Title = "Thêm nhân viên mới";
    Layout = "~/Areas/Admin/Views/Shared/_layoutadmin.cshtml";
}

@using (Html.BeginForm("Create", "NhanVien", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm mới nhân viên</h4>
        <hr>
        <div class="row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group col-md-3">
                <label class="control-label">Họ và tên </label>
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Email</label>
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Mật khẩu </label>
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Chọn chức vụ </label>
                @Html.DropDownList("MaChucVu", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaChucVu, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-md-3">
                <label class="control-label">Ngày sinh </label>
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @type = "date", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })

            </div>

            <div class="form-group col-md-3">
                <label class="control-label">Địa chỉ thường trú </label>
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-md-3">
                <label class="control-label">Số điện thoại </label>
                @Html.EditorFor(model => model.Sdt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sdt, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Giới tính là nam ? </label>
                <div class="checkbox">
                    @Html.EditorFor(model => model.Sex, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-12">
                <label class="control-label">Ảnh sản phẩm</label>
                <div id="myfileupload">
                    <input type="file" name="file" id="file" style="width: 100%;" />
                    @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
                </div>
                <div id="thumbbox">
                    <img height="450" width="400" alt="Thumb image" id="thumbimage"
                         style="display: none" />
                    <a class="removeimg" href="javascript:"></a>
                </div>
                <div id="boxchoice">
                    <a href="javascript:" class="Choicefile">
                        <i class="fas fa-cloud-upload-alt"></i>
                        Chọn ảnh
                    </a>
                    <p style="clear:both"></p>
                </div>
                <input type="submit" value="Tạo nhân viên" class="btn btn-save" />
                <a class="btn btn-cancel" href="@Url.Action("Index","NhanVien")">Hủy bỏ</a>
            </div>
          
        </div>
    </div>
}

Nike/Areas/Admin/Views/NhanVien/Delete.cshtml
@model Nike.Models.NhanVien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_layoutadmin.cshtml";
}



<div class="confirm__delete">
    <h3>Bạn có chắc muốn xóa đi nhân viên này ?</h3>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-save" />
            @Html.ActionLink("Quay về", "Index", null, new { @class = "btn btn-cancel" })
        </div>
    }
</div>

<style>
    .confirm__delete {
        padding: 250px 300px;
        background-color: rgb(166 200 236);
    }
</style>

Nike/Areas/Admin/Views/NhanVien/Detail.cshtml
@model Nike.Models.NhanVien
@{

    ViewBag.Title = "Thông tin cá nhân";
    Layout = "~/Areas/Admin/Views/Shared/_layoutadmin.cshtml";
}

<div class="app-title">
    <ul class="app-breadcrumb breadcrumb side">
        <li class="breadcrumb-item active"><a href="#"><b>Nhân viên: #@Model.Id</b></a></li>
    </ul>
    <div id="clock"></div>
</div>

<div class="row detail">
    <div class="col-md-4 detail__avatar">
        <img src="~/Hinh/NhanVien/@Model.Picture" alt="Ảnh đại diện" />
    </div>
    <div class="col-md-8">
        <div class="detail__item">
            <label class="control-label">Họ và tên: </label>
            @Model.FullName
        </div>
        <div class="detail__item">
            <label class="control-label">Email: </label>
            @Model.Email
        </div> <div class="detail__item">
            <label class="control-label">Địa chỉ thường trú: </label>
            @Model.Address
        </div> <div class="detail__item">
            <label class="control-label">Ngày sinh: </label>
            @(Model.NgaySinh?.ToString("dd/MM/yyyy"))
        </div> <div class="detail__item">
            <label class="control-label">Số điện thoại: </label>
            @Model.Sdt
        </div>
       <div class="detail__item">
            <label class="control-label">Chức vụ: </label>
            @Model.ChucVu.ChucVu1
        </div>
    <div class="detail__item">
        <label class="control-label">Giới tính: </label>
        @{
            if (Model.Sex == true)
            {
                <text>Nam</text>
            }
            else
            {
                <text>Nữ</text>
            }
        }
    </div>
    <div class="row btn">
        <button class="btn btn-save btn-sm edit" type="button" title="Sửa"
                onclick="location.href='@Url.Action("Edit", "NhanVien",new { id = Model.Id })'">
            Chỉnh sửa thông tin
        </button>
        <a class="btn btn-cancel" href="@Url.Action("Index","NhanVien")">Hủy bỏ</a>
    </div>
</div>

<style>
    .detail{
        display: flex;
        align-items: center;
        justify-content: center;
    }
    detail__avatar{
        
    }
    .detail__avatar img {
        height: 80%;
        width: 80%;
        object-fit: cover;
    }
    .detail__item {
        margin: 20px 0;
        display: block;
        width: 100%;
        padding: 0.375rem 0.75rem;
        font-size: 15px;
        line-height: 1.5;
        color: black;
        background-color: #f1f1f1;
        background-clip: padding-box;
        height: 45px;
        border: 1px solid #dadada;
        border-radius: .357rem;
    }
</style>

Nike/Areas/Admin/Views/NhanVien/Edit.cshtml
@model Nike.Models.NhanVien

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_layoutadmin.cshtml";
}

<h2>Chỉnh sửa thông tin nhân viên</h2>
<div class="form-horizontal">
    <h4>Mã nhân viên: @Model.Id</h4>
    <hr />
    @using (Html.BeginForm("Edit", "NhanVien", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group col-md-3">
                <label class="control-label">Họ và tên </label>
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Email</label>
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "abcdef@gmail.com" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Mật khẩu </label>
                @Html.EditorFor(model => model.Password, new
                {
                    htmlAttributes = new
                    {@*@type = "password",*@@class = "form-control"
}
})
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Chức Vụ </label>
                @Html.DropDownList("MaChucVu", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaChucVu, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-md-3">
                <label class="control-label">Ngày sinh </label>
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @type = "date", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })

            </div>

            <div class="form-group col-md-3">
                <label class="control-label">Địa chỉ thường trú </label>
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-md-3">
                <label class="control-label">Số điện thoại </label>
                @Html.EditorFor(model => model.Sdt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sdt, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Giới tính là nam ? </label>
                <div class="checkbox">
                    @Html.EditorFor(model => model.Sex, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group col-md-12">
                <label class="control-label">Ảnh đại diện</label>
                <div id="myfileupload">
                    <input type="file" name="file" id="file" style="width: 100%;" />
                    @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
                </div>
                <div id="thumbbox">
                    <img height="450" width="400" alt="Thumb image" id="thumbimage"
                         style="display: none" />
                    <a class="removeimg" href="javascript:"></a>
                </div>
                <div id="boxchoice">
                    <a href="javascript:" class="Choicefile">
                        <i class="fas fa-cloud-upload-alt"></i>
                        Chọn ảnh
                    </a>
                    <p style="clear:both"></p>
                </div>
                <input type="submit" value="Chỉnh Sửa" class="btn btn-save" />
                <a class="btn btn-cancel" href="@Url.Action("Index","NhanVien")">Hủy bỏ</a>
            </div>


        </div>
    }
</div>

Nike/Areas/Admin/Views/NhanVien/Index.cshtml
@model IEnumerable<Nike.Models.NhanVien>

@{
    ViewBag.Title = "Quản Lí Nhân Viên";
    Layout = "~/Areas/Admin/Views/Shared/_layoutadmin.cshtml";
}

<div class="app-title">
    <ul class="app-breadcrumb breadcrumb side">
        <li class="breadcrumb-item active"><a href="#"><b>Danh sách nhân viên</b></a></li>
    </ul>
    <div id="clock"></div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">

                <div class="row element-button">
                    <div class="col-sm-2" style="display:flex;align-items:center">
                        <a class="btn btn-add btn-sm" href="@Url.Action("Create","NhanVien")" title="Thêm">
                            <i class="fas fa-plus"></i>
                            Tạo mới nhân viên
                        </a>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 col-md-6">

                    </div>
                    <div class="col-sm-12 col-md-6">
                        @* Tìm kiếm nhân viên  *@
                        @using (Html.BeginForm("Index", "NhanVien", FormMethod.Get, new { @class = "dataTables_filter d-flex justify-content-end" }))
                        {
                            <label>
                                Tìm kiếm:

                                @Html.TextBox("searchString", null, new { @class = "form-control form-control-sm", @placeholder = "Nhập họ tên" })

                            </label>
                        }
                    </div>
                </div>
                <dov class="row">
                    <table class="table table-hover table-bordered js-copytextarea" cellpadding="0" cellspacing="0" border="0"
                           id="sampleTable">
                        <thead>
                            <tr class="label">
                                <th>ID</th>
                                <th>Họ và tên</th>
                                <th>Ảnh thẻ</th>
                                <th>Địa chỉ</th>
                                <th>Giới tính</th>
                                <th>SĐT</th>
                                <th>Chức vụ</th>
                                <th>Tính năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.NhanVien)
                            {
                                <tr>

                                    <td>@item.Id</td>
                                    <td>@item.FullName</td>
                                    <td>
                                        @if (item.Picture == null)
                                        {
                                            <img src="~/Hinh/user.jpg" alt="Image" width="100" height="100" />

                                        }
                                        else
                                        {
                                            <img src="~/Hinh/NhanVien/@Url.Content(@item.Picture)" alt="Image" width="100" height="100" />
                                        }
                                    </td>
                                    <td>@item.Address </td>
                                    @{
                                        if (item.Sex == true)
                                        {
                                            <td>Nam</td>
                                        }
                                        else
                                        {
                                            <td>Nữ</td>
                                        }
                                    }
                                    <td>@item.Sdt</td>
                                    <td>@item.ChucVu.ChucVu1</td>
                                    <td class="table-td-center">
                                        <button class="btn btn-primary btn-sm trash" type="button" title="Xóa"
                                                onclick="location.href='@Url.Action("Delete", "NhanVien",new { id = item.Id })'">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                        <button class="btn btn-primary btn-sm edit" type="button" title="Sửa"
                                                onclick="location.href='@Url.Action("Edit", "NhanVien",new { id = item.Id })'">
                                            <i class="fas fa-edit"></i>
                                        </button>
                                        <button class="btn btn-primary btn-sm user-btn" type="button" title="Xem thông tin"
                                                onclick="location.href='@Url.Action("Detail", "NhanVien",new { id = item.Id })'">
                                            <i class="fas fa-user"></i>
                                        </button>

                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </dov>

            </div>
        </div>
    </div>
</div>

<style>
    tr.label th {
        text-align: center;
    }
    td img {
        object-fit: cover
    }
</style>